// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package weatherdb

import (
	"time"
)

type Weather struct {
	ID          int32
	Geohash     string
	Temperature float64
	Humidity    float64
	Elevation   float64
	CreatedAt   time.Time
}
