// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package weatherdb

import (
	"context"
	"time"
)

const getWeather = `-- name: GetWeather :one
SELECT created_at, temperature, humidity, elevation
FROM weather
WHERE geohash = $1 AND created_at BETWEEN NOW() - INTERVAL '5 minutes' AND NOW()
`

type GetWeatherRow struct {
	CreatedAt   time.Time
	Temperature float64
	Humidity    float64
	Elevation   float64
}

func (q *Queries) GetWeather(ctx context.Context, geohash string) (GetWeatherRow, error) {
	row := q.db.QueryRowContext(ctx, getWeather, geohash)
	var i GetWeatherRow
	err := row.Scan(
		&i.CreatedAt,
		&i.Temperature,
		&i.Humidity,
		&i.Elevation,
	)
	return i, err
}

const setWeather = `-- name: SetWeather :exec
INSERT INTO 
weather (geohash, temperature, humidity, elevation)
VALUES ($1, $2, $3, $4)
ON CONFLICT (geohash)
DO UPDATE SET
temperature = EXCLUDED.temperature,
humidity = EXCLUDED.humidity,
elevation = EXCLUDED.elevation,
created_at = now()
`

type SetWeatherParams struct {
	Geohash     string
	Temperature float64
	Humidity    float64
	Elevation   float64
}

func (q *Queries) SetWeather(ctx context.Context, arg SetWeatherParams) error {
	_, err := q.db.ExecContext(ctx, setWeather,
		arg.Geohash,
		arg.Temperature,
		arg.Humidity,
		arg.Elevation,
	)
	return err
}
