// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pb/weather/v1/weather.proto

package weatherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetWeatherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherRequest) Reset() {
	*x = GetWeatherRequest{}
	mi := &file_pb_weather_v1_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherRequest) ProtoMessage() {}

func (x *GetWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_weather_v1_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetWeatherRequest) Descriptor() ([]byte, []int) {
	return file_pb_weather_v1_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetWeatherRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetWeatherRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type GetWeatherResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float64                `protobuf:"fixed64,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float64                `protobuf:"fixed64,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Elevation     float64                `protobuf:"fixed64,3,opt,name=elevation,proto3" json:"elevation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWeatherResponse) Reset() {
	*x = GetWeatherResponse{}
	mi := &file_pb_weather_v1_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWeatherResponse) ProtoMessage() {}

func (x *GetWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_weather_v1_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetWeatherResponse) Descriptor() ([]byte, []int) {
	return file_pb_weather_v1_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetWeatherResponse) GetTemperature() float64 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GetWeatherResponse) GetHumidity() float64 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *GetWeatherResponse) GetElevation() float64 {
	if x != nil {
		return x.Elevation
	}
	return 0
}

var File_pb_weather_v1_weather_proto protoreflect.FileDescriptor

const file_pb_weather_v1_weather_proto_rawDesc = "" +
	"\n" +
	"\x1bpb/weather/v1/weather.proto\x12\n" +
	"weather.v1\"M\n" +
	"\x11GetWeatherRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\"p\n" +
	"\x12GetWeatherResponse\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x01R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x01R\bhumidity\x12\x1c\n" +
	"\televation\x18\x03 \x01(\x01R\televation2]\n" +
	"\x0eWeatherService\x12K\n" +
	"\n" +
	"GetWeather\x12\x1d.weather.v1.GetWeatherRequest\x1a\x1e.weather.v1.GetWeatherResponseB)Z'weather-tracker/pb/weather/v1;weatherv1b\x06proto3"

var (
	file_pb_weather_v1_weather_proto_rawDescOnce sync.Once
	file_pb_weather_v1_weather_proto_rawDescData []byte
)

func file_pb_weather_v1_weather_proto_rawDescGZIP() []byte {
	file_pb_weather_v1_weather_proto_rawDescOnce.Do(func() {
		file_pb_weather_v1_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_weather_v1_weather_proto_rawDesc), len(file_pb_weather_v1_weather_proto_rawDesc)))
	})
	return file_pb_weather_v1_weather_proto_rawDescData
}

var file_pb_weather_v1_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_weather_v1_weather_proto_goTypes = []any{
	(*GetWeatherRequest)(nil),  // 0: weather.v1.GetWeatherRequest
	(*GetWeatherResponse)(nil), // 1: weather.v1.GetWeatherResponse
}
var file_pb_weather_v1_weather_proto_depIdxs = []int32{
	0, // 0: weather.v1.WeatherService.GetWeather:input_type -> weather.v1.GetWeatherRequest
	1, // 1: weather.v1.WeatherService.GetWeather:output_type -> weather.v1.GetWeatherResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_weather_v1_weather_proto_init() }
func file_pb_weather_v1_weather_proto_init() {
	if File_pb_weather_v1_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_weather_v1_weather_proto_rawDesc), len(file_pb_weather_v1_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_weather_v1_weather_proto_goTypes,
		DependencyIndexes: file_pb_weather_v1_weather_proto_depIdxs,
		MessageInfos:      file_pb_weather_v1_weather_proto_msgTypes,
	}.Build()
	File_pb_weather_v1_weather_proto = out.File
	file_pb_weather_v1_weather_proto_goTypes = nil
	file_pb_weather_v1_weather_proto_depIdxs = nil
}
