CREATE TABLE IF NOT EXISTS weather (
  id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  geohash VARCHAR(12) NOT NULL UNIQUE,
  temperature DOUBLE PRECISION NOT NULL,
  humidity DOUBLE PRECISION NOT NULL,
  elevation DOUBLE PRECISION NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
